#%RAML 1.0 DataType

mediaType: application/json
types:
  account1_5:
    properties:
        id?:
          type: integer
          description: Internal ID of an account
        operationalId?:         
          type: integer | nil
          description: Operational ID of an account
        name: 
          type: string
          description: Name of Account
        passive?: 
          type: integer
          description: Active or passive state of account
        owner?: 
          type: integer
          description: Responsible id of an account
        type?: 
          type: integer | nil
          description: Type of an account
        vatId?: 
          type: string
          description: VAT id of an account
        businessId?: 
          type: string
          description: Business id of an account
        termsOfPayment?: 
          type: integer 
          description: Terms of payment of an invoice
        phone?: 
          type: string
          description: Phone number of an account
          pattern: "^[0-9|-]+$"
        fax?: 
          type: string
          description: Fax number of an account
        website?: 
          type: string
          description: Website of an account
        email?: 
          type: string
          pattern: "^\\w+(\\.\\w+)?@company.com"
          description: Email address of an account
        parentAccountName: 
          type: string
          required: false
        industry?: integer | nil
        serviceLevel?: 
          type: integer | nil
          description: Service level provided to real company linked to an account
        customerSatisfaction?: integer | nil
        invoiceChannel?: 
          type: integer | nil
          description: Methods of delivery of invoices
        invoiceVat?: 
          type: number | nil
          description: VAT on an invoice of an account
        invoiceNetOperator?: string
        eInvoiceAddress?: 
          type: string
          description: Party identification number
        handlingFee?: 
          type: number | nil
          description: Handling fee of an account
        invoiceEmail?: 
          type: string
          description: Invoice delivery email
          pattern: "^\\w+(\\.\\w+)?@company.com"
        supplierAccount?: 
          type: integer | nil
          description: Supplier id of an account
        twitter?: 
          type: string
          description: Twitter name of an account
        facebook?: 
          type: string
          description: Facebook name of an account
        blog?: 
          type: string
          description: Blog address of an account
        combineInvoices?: integer | nil
        rfReferenceNumber?: integer | nil 
        lineOfBusiness?: integer | nil
        activeContacts?: integer
        billingAddress?: 
          type: string
          description: Invoice billing address of an account
        billingCity?: 
          type: string
          description: Invoice billing city of an account
        billingCountry?: 
          type: integer | nil
          description: Invoice billing country of an account
        billingPostalCode?: 
          type: string
          description: Invoice billing postal code of an account
        created?: 
          type: datetime
          format: RFC3339 
        createdBy?: string | integer | nil
        modified?: 
          type: datetime
          format: RFC3339
        modifiedBy?: string | integer | nil
        ownerName?: string | integer | nil       
        revenueThisYear?: number | nil
        revenueLastYear?: number | nil
        shippingAddress?: 
          type: string
          description: Invoice shipping address of an account
        shippingCity?: 
          type: string
          description: Invoice shipping city of an account
        shippingCountry?: 
          type: integer | nil
          description: Invoice shipping country of an account
        shippingPostalCode?: 
          type: string
          description: Invoice shipping postal code of an account
        supplierAccountName?: 
          type: string
          description: Account name of supplier